### ISSUE TITLE
Unexpectedly takes root password from ~/.my.cnf

### ISSUE THREAD

**Issue by llehtinen** [wix/wix-embedded-mysql#104]
My attempts to start the embedded server failed with the following error:
```
Exception in thread "main" com.wix.mysql.exceptions.CommandFailedException: Command 'CREATE USER 'auser'@'%' IDENTIFIED BY 'sa';' on schema 'information_schema' failed with errCode '1' and output 'ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
'
	at com.wix.mysql.MysqlClient.execute(MysqlClient.java:65)
	at com.wix.mysql.MysqlClient.executeCommands(MysqlClient.java:43)
	at com.wix.mysql.EmbeddedMysql.<init>(EmbeddedMysql.java:46)
	at com.wix.mysql.EmbeddedMysql$Builder.start(EmbeddedMysql.java:131)
```
It seems the root password was being read from `~/.my.cnf`, which looked something like this:
```
[mysql]
host=127.0.0.1
port=13306
user=root
password=****
```
After renaming the file the embedded server starts fine, but I'd like to keep my default options for command line usage.

**Comment by viliusl** [comment]
@llehtinen - which version of mysql ar you using? 5.6 or 5.7?

**Comment by llehtinen** [comment]
I tried with both `v5_6_latest` and `v5_7_latest`

**Comment by viliusl** [comment]
@llehtinen - I tried reproducing it locally (by adding `.my.cnf` to `~`), but to no avail. At least `wix-embedded-mysql` tests pass with no probs. I mean I would like to set-up ci in a way to make build fail and then have a fix. Maybe you should share your complete `.my.cnf` (without passwords) so I can try to reproduce or snippet of code/project to add both `.my.cnf` and additional test?
