### ISSUE TITLE
Unable to start v5_7_latest on Windows

### ISSUE THREAD

**Issue by rodionLev** [wix/wix-embedded-mysql#157]
OS: Windows 10
Java version: build 1.8.0_181-b13
Library version: 4.2.0
MySQL version: v5_7_19 (latest)

Hello,
I got next error when tried to use wix with spring boot app integration tests:
```
...
12-18 17:32:54.062 INFO  Preparing EmbeddedMysql version 'Version 5.7.19'...
12-18 17:32:54.167 INFO  Preparing mysqld for startup

java.lang.RuntimeException: Command exited with error code: '-1073741515' and output: ''

	at com.wix.mysql.distribution.setup.ProcessRunner.resolveException(ProcessRunner.java:53)
	at com.wix.mysql.distribution.setup.ProcessRunner.run(ProcessRunner.java:38)
	at com.wix.mysql.distribution.setup.Mysql57Initializer.apply(Mysql57Initializer.java:35)
	at com.wix.mysql.distribution.Setup.apply(Setup.java:26)
	at com.wix.mysql.MysqldExecutable.start(MysqldExecutable.java:42)
	at com.wix.mysql.MysqldExecutable.start(MysqldExecutable.java:21)
	at de.flapdoodle.embed.process.runtime.Executable.start(Executable.java:108)
	at com.wix.mysql.EmbeddedMysql.<init>(EmbeddedMysql.java:47)
	at com.wix.mysql.EmbeddedMysql$Builder.start(EmbeddedMysql.java:169)
	at com.wix.mysql.EmbeddedMysql$Builder$start.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
	at com.abcfinancial.api.common.test.BaseTest.setupWixDb(BaseTest.groovy:281)
	at com.abcfinancial.api.common.test.BaseTest.setupSuite(BaseTest.groovy:241)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:326)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:67)
...
```

I tried to check mysqld version manually, running command:
```target\mysql-5.7-7a846738-80ab-4d9d-8b2c-0f9dac26f1a0\bin>mysql.exe --version```

and got 2 UI popups with messages:
```The code execution cannot proceed because MSVCR120.dll was not found.```
```The code execution cannot proceed because MSVCP120.dll was not found.```

Please note that I can switch to v5_7_13 version without any with changes in my code.
Can you help me with that issue?

**Comment by skovtunenko** [comment]
Looks like this might be related to the:

> Known issues
> starting version 5.7.18, Microsoft Visual C++ 2013 Redistributable Package needs to be pre-installed on windows.

**Comment by steve-perkins** [comment]
Are the dependencies listed in the README still current and/or complete?  I am experiencing the same "-1073741515" issue at the original submitter, using MySQL 8.0.17 on Windows 10.  

I have installed the x64 version of the Microsoft Visual C++ 2013 Redistributable Package.  I have also installed the 2015/2017/2019 bundle (those all come together in the same installer).

In case it matters, my machine has an AMD Ryzen 5 processor.  I found a [special update for the VC 2013 redistributables](https://support.microsoft.com/en-us/help/3179560/update-for-visual-c-2013-and-visual-c-redistributable-package), for processors that don't support certain expected CPU instructions.  I thought that was a long shot though, and the update indeed made no difference.

**Unlike** the original submitter with MySQL 5.7.19, I don't get any error messages when I attempt to run the uncompressed 8.0.17 executables directly.  `mysqld.exe` just silently exits, while `mysql.exe` and `mysqladmin.exe` appear to work perfectly fine (although they can't do much if the daemon's not running).

Also, I happen to have the current version of MySQL community edition (i.e. 8.0.18) installed and running on this same machine.  The OS can run MySQL 8.x just fine.  It just can't run the wix-embedded version of it on a separate port, for some reason.  Temporarily shutting down the installed MySQL instance also makes no difference.
