### ISSUE TITLE
It can not work in Alpine environment

### ISSUE THREAD

**Issue by xz1996** [wix/wix-embedded-mysql#172]
I run my test in a docker container who's based on alpine, and I also install the ```libaio```, but it always report

`
 Caused by: java.io.IOException: error=2, No such file or directory
    at java.lang.UNIXProcess.forkAndExec(Native Method)
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
    at java.lang.ProcessImpl.start(ProcessImpl.java:134)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
`

While, when I run it in ubuntu container, it works, so I hope you can handle this problem and support more system, thanks.

**Comment by viliusl** [comment]
@xz1996 - it's due to directions mysql is taking - meaning it uses dlibs instead of bundled binaries in newer mysql versions. For alpine you should ensure that libs mentioned in https://github.com/wix/wix-embedded-mysql#known-issues are present.
