### ISSUE TITLE
MySql distribution is "Moved Permanently"

### ISSUE THREAD

**Issue by karayv** [wix/wix-embedded-mysql#198]
```
        mysqld = EmbeddedMysql.anEmbeddedMysql(Version.v5_6_23) //
                .addSchema("mydb") //
                .start();
```
throws an exception.

```
> less mysql-5.6.24-osx10.9-x86_64.tar.gz

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://dev.mysql.com/get/Downloads/MySQL-5.6/mysql-5.6.24-osx10.9-x86_64.tar.gz">here</a>.</p>
</body></html>
```

Stacktrace:
```
Caused by: de.flapdoodle.embed.process.exceptions.DistributionException: java.io.IOException: File /Users/akaraivanskyi/.embedmysql/MySQL-5.6/mysql-5.6.23-osx10.9-x86_64.tar.gz
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:68)
	at com.wix.mysql.EmbeddedMysql.<init>(EmbeddedMysql.java:32)
	at com.wix.mysql.EmbeddedMysql$Builder.start(EmbeddedMysql.java:112)
	at com.metadata.service.config.EmbeddedMySqlConfig.setup(EmbeddedMySqlConfig.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
	... 113 more
Caused by: java.io.IOException: File /Users/akaraivanskyi/.embedmysql/MySQL-5.6/mysql-5.6.23-osx10.9-x86_64.tar.gz
	at de.flapdoodle.embed.process.extract.AbstractExtractor.archiveStreamWithExceptionHint(AbstractExtractor.java:52)
	at de.flapdoodle.embed.process.extract.AbstractExtractor.extract(AbstractExtractor.java:64)
	at de.flapdoodle.embed.process.store.ArtifactStore.extractFileSet(ArtifactStore.java:74)
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:56)
	... 123 more
Caused by: java.util.zip.ZipException: Not in GZIP format
	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:165)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
	at org.apache.commons.compress.compressors.gzip.GzipCompressorInputStream.<init>(GzipCompressorInputStream.java:43)
	at de.flapdoodle.embed.process.extract.TgzExtractor.archiveStream(TgzExtractor.java:43)
	at de.flapdoodle.embed.process.extract.AbstractExtractor.archiveStreamWithExceptionHint(AbstractExtractor.java:46)
	... 126 more

```

**Comment by karayv** [comment]
Really old version of the lib is used by mistake. Closing the issue.
