### ISSUE TITLE
M1 macbook Java 8 Could not open inputStream for https://dev.mysql.com/get/Downloads//MySQL-5.7/mysql-5.7.15-osx10.11-x86.tar.gz

### ISSUE THREAD

**Issue by michaeljamieson10** [wix/wix-embedded-mysql#209]
Could not find any links for mysql, switched versions of mysql and still same error. 
java.io.IOException: Could not open inputStream for https://dev.mysql.com/get/Downloads//MySQL-5.7/mysql-5.7.15-osx10.11-x86.tar.gz
de.flapdoodle.embed.process.exceptions.DistributionException: java.io.IOException: Could not open inputStream for https://dev.mysql.com/get/Downloads//MySQL-5.7/mysql-5.7.15-osx10.11-x86.tar.gz
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:69)
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:49)
	at com.wix.mysql.EmbeddedMysql.<init>(EmbeddedMysql.java:41)
	at com.wix.mysql.EmbeddedMysql$Builder.start(EmbeddedMysql.java:169)
	at com.grassp.restservice.api.v1.controller.GrasspControllerTest.startEmbeddedMysqld(GrasspControllerTest.java:133)
	at com.grassp.restservice.api.v1.ControllersTestSuite.setup(ControllersTestSuite.java:62)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.io.IOException: Could not open inputStream for https://dev.mysql.com/get/Downloads//MySQL-5.7/mysql-5.7.15-osx10.11-x86.tar.gz
	at de.flapdoodle.embed.process.store.Downloader.downloadInputStream(Downloader.java:131)
	at de.flapdoodle.embed.process.store.Downloader.download(Downloader.java:69)
	at de.flapdoodle.embed.process.store.ArtifactStore.checkDistribution(ArtifactStore.java:66)
	at de.flapdoodle.embed.process.store.ExtractedArtifactStore.checkDistribution(ExtractedArtifactStore.java:60)
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:56)
	... 42 more
Caused by: java.io.FileNotFoundException: https://dev.mysql.com/get/Downloads//MySQL-5.7/mysql-5.7.15-osx10.11-x86.tar.gz
	at de.flapdoodle.embed.process.store.Downloader.downloadInputStream(Downloader.java:127)
	... 46 more

**Comment by michaeljamieson10** [comment]
The current OS on the device is 11.0 big sur and also has a m1 arm chip. It is able to work with the sql versions through an emulator called rosetta 2

**Comment by martin-g** [comment]
I am facing the same issue on Linux ARM64.

Lately I am working on improving FlapDoodle Process and Mongo to add support for ARM64 and better handling of new Mongo. versions:
https://github.com/flapdoodle-oss/de.flapdoodle.embed.process/pull/119 - Add support for AARCH64
https://github.com/flapdoodle-oss/de.flapdoodle.embed.process/pull/120 - Add support for comparing version
https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/pull/343 - Add support for Linux AARCH64 and newer Mongodb versions

I will see what is needed to do here. I hope there is someone to review and merge my work!

**Comment by grunzwei** [comment]
hey all,
i had the same issue, when using open jdk.
i downloaded oracle sdk x64 and run it (on big sur, that includes rosetta2 built in) and it seems to work.
this is a possible workaround, for non production environments.
FYI

**Comment by michaeljamieson10** [comment]
this worked!!! You just saved me so much time!!!!!
