### ISSUE TITLE
Cannot run as root user with non blank password

### ISSUE THREAD

**Issue by michaelruocco** [wix/wix-embedded-mysql#58]
I have noticed that it is not possible to connect to embedded MySQL using the username root and providing a non empty string password. It works fine if the password is empty string but if I use anything other value it fails to connect.

Is this because MySQL does not allow you to have a root user with a blank password? I suspect that it is, in which case feel free to close this issue but I just wanted to check whether it was something you knew about already?

I have created a repo here which demonstrates the issue, there are 4 tests, 3 work fine and 1 fails.

https://github.com/michaelruocco/embedded-mysql-password-issue

When the test fails it throws the following error when trying to connect to the embedded MySQL instance.

```
java.sql.SQLException: Cannot create PoolableConnectionFactory (Access denied for user 'root'@'localhost' (using password: YES))
	at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:2294)
	at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:2039)
	at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:1533)
	at uk.co.tpplc.PasswordTest.testConnection(PasswordTest.java:60)
	at uk.co.tpplc.PasswordTest.shouldConnectWithRootUserAndPassword(PasswordTest.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:253)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:695)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:663)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:653)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:115)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:1663)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:662)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:352)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:221)
	at org.apache.commons.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:39)
	at org.apache.commons.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:256)
	at org.apache.commons.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:2304)
	at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:2290)
	... 31 more
```

**Comment by viliusl** [comment]
Hej, thanks for perfect issue report:)

Funny thing is tests do pass for me, but I pretty much know the reason.

To initialize mysqld service I use defaults that is:
 - 'root'@'localhost' and null/empty password.

Then I create user you instruct me using these credentials, but I do it a bit differently, say when you do `testConnection("root", "");`, then I crete user 'root'@'%' with empty password.

What you have encountered is:
 - `testConnection("root", "")` creates 'root'@'%' with empty password but on jdbc connection picks up existing system user ('root'@'localhost') and passwords do match;
 - `testConnection("root", "1234")` creates 'root'@'%' with '1234' password but on jdbc connection picks up existing system user ('root'@'localhost') and passwords do not match anymore;

My local setup is a bit messed up, so I hit 'root'@'%' mapping and tests pass.

Now help me out here with a solution for this, because I see multiple ways to fix it, but cannot decide on which is best:
 1. forbid usage of 'root' user altogether with clear exception/error message;
 2. be ok if developer uses `.withUser('root', '')` but throw exception if password is not null/empty.
 3. ?

I personally would go with # 1 - it's not really friendly and is restrictive, but there are no surprises there and developers should understand:) wdyt?

**Comment by michaelruocco** [comment]
Hi,

I was expecting something along those lines to be honest but thanks for the detailed explanation, it makes it a bit clearer for me.

It is a bit of a tricky one to decide but I would be inclined to go with option 1 as well I think.

Firstly it is simpler to understand "root user not allowed" than "root user not allowed as long as you don't want to provide a password" and probably slightly simpler to implement.

Secondly, when spinning up an embedded server for testing, as long as you use the same username and password combination when connecting as you do when starting up it shouldn't really matter whether the user is root or not.

Finally it is bad practice to connect as a route user when connecting to the actual database anyway, so I see no harm in discouraging it in testing as well.

Obviously as you say it is not particularly friendly and a bit restrictive but the same could be said of option 2 as well and at least it is simpler, plus I don't really have any ideas for a 3rd option!

**Comment by viliusl** [comment]
@michaelruocco - 1 it is, thanks!

I suppose it's not a pressing matter for you, so will not rush this, but hopefully soonish as it's a quick one to fix.

**Comment by michaelruocco** [comment]
@viliusl Correct, not pressing at all for me, I will update the person that raised it against my plugin to let them know what is happening. I have already advised that changing the username or using a blank password should suffice as a work around.

Thanks.
